# permissions for end users to view botmessages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: botmessage-viewer-role
rules:
- apiGroups:
  - telegram.my.domain
  resources:
  - botmessages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telegram.my.domain
  resources:
  - botmessages/status
  verbs:
  - get
